=== svenreimers/hg-netbeans-org-main-contrib/vcs.advanced/src/org/netbeans/modules/vcs/profiles/config/vcs-configuration-1_1.dtd
<!--
-//NetBeans//DTD VCS Configuration 1.1//EN
http://www.netbeans.org/dtds/vcs-configuration-1_1.dtd
XML representation of a VCS commands and variables configuration profile
-->
<!--
The contents of this file are subject to the terms of the Common Development
and Distribution License (the License). You may not use this file except in
compliance with the License.

You can obtain a copy of the License at http://www.netbeans.org/cddl.html
or http://www.netbeans.org/cddl.txt.

When distributing Covered Code, include this CDDL Header Notice in each file
and include the License file at http://www.netbeans.org/cddl.txt.
If applicable, add the following below the CDDL Header, with the fields
enclosed by brackets [] replaced by your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

The Original Software is NetBeans. The Initial Developer of the Original
Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
Microsystems, Inc. All Rights Reserved.
-->

<!ELEMENT configuration    (label, resourceBundle?, os?, (condition)*, variables, commands, globalCommands?)   >
<!ELEMENT resourceBundle   (#PCDATA)   >
<!ELEMENT label            (#PCDATA)   >
<!ELEMENT os               (compatible?, uncompatible?)   >
<!ELEMENT compatible       (#PCDATA)   >
<!ELEMENT uncompatible     (#PCDATA)   >
<!ELEMENT condition        (var|and|or|not)*   >
<!ELEMENT var              EMPTY   >
<!ELEMENT and              (var|and|or|not)*   >
<!ELEMENT or               (var|and|or|not)*   >
<!ELEMENT not              (var)   >
<!ELEMENT variables        (variable)*   >
<!ELEMENT commands         (command|separator)*   >
<!ELEMENT globalCommands   (command)*   >
<!ELEMENT variable         (value)*   >
<!ELEMENT command          (command|separator|property)*   >
<!ELEMENT separator        EMPTY   >
<!ELEMENT property         (value)*   >
<!ELEMENT value            (#PCDATA)   >

<!ATTLIST configuration
          type             CDATA #IMPLIED   >
          
<!ATTLIST condition
          var              CDATA #REQUIRED   >

<!ATTLIST var
          name             CDATA #REQUIRED
          value            CDATA #IMPLIED
          valueIgnoreCase  CDATA #IMPLIED
          valueContains    CDATA #IMPLIED
          valueContainsIgnoreCase  CDATA #IMPLIED   >

<!ATTLIST variable
          name             CDATA #REQUIRED
          basic            CDATA #IMPLIED
          label            CDATA #IMPLIED
          labelMnemonic    CDATA #IMPLIED
          localFile        CDATA #IMPLIED
          localDir         CDATA #IMPLIED
          executable       CDATA #IMPLIED
          order            CDATA #IMPLIED
          selector         CDATA #IMPLIED
          if               CDATA #IMPLIED
          unless           CDATA #IMPLIED   >

<!ATTLIST command
          name             CDATA #REQUIRED
          displayName      CDATA #IMPLIED                                                                                    
          if               CDATA #IMPLIED
          unless           CDATA #IMPLIED     >

<!ATTLIST property
          name             CDATA #REQUIRED
          if               CDATA #IMPLIED
          unless           CDATA #IMPLIED    >

<!ATTLIST value
          xml:space        CDATA #IMPLIED
          if               CDATA #IMPLIED
          unless           CDATA #IMPLIED    >

=== svenreimers/hg-netbeans-org-main-contrib/vcs.profiles.vss/src/org/netbeans/modules/vcs/profiles/vss/config/vss.xml
<?xml version="1.0"?>
<!DOCTYPE configuration PUBLIC '-//NetBeans//DTD VCS Configuration 1.1//EN' 'http://www.netbeans.org/dtds/vcs-configuration-1_1.dtd'>
<!--
                Sun Public License Notice

The contents of this file are subject to the Sun Public License
Version 1.0 (the "License"). You may not use this file except in
compliance with the License. A copy of the License is available at
http://www.sun.com/

The Original Code is NetBeans. The Initial Developer of the Original
Code is Sun Microsystems, Inc. Portions Copyright 1997-2004 Sun
Microsystems, Inc. All Rights Reserved.
-->


<configuration>
  <label>getBundle(org/netbeans/modules/vcs/profiles/vss/config/Bundle).getString(VSS_Label)</label>
  
  <os>
    <compatible>"Windows"</compatible>
  </os>
  
  <condition var="IS_WINDOWS">
    <var name="os.name" valueContainsIgnoreCase="WINDOWS"/>
  </condition>
  
  <condition var="IS_WIN9X">
    <or>
      <var name="os.name" value="Windows 95"/>
      <var name="os.name" value="Windows 98"/>
      <var name="os.name" value="Windows Me"/>
    </or>
  </condition>
  
  <condition var="IS_WINNT">
    <var name="IS_WINDOWS" value="true"/>
    <not>
      <var name="IS_WIN9X" value="true"/>
    </not>
  </condition>
  
  <variables>
    <variable name="FS_DISPLAY_NAME" basic="false">
      <value>VSS</value>
    </variable>
    <variable name="MODULE_INFORMATION_CODE_NAME_BASE" basic="false">
      <value>org.netbeans.modules.vcs.profiles.vss</value>
    </variable>
    <variable name="LOCAL_FILES_FILTERED_OUT_CASE_SENSITIVE" basic="false">
      <value>false</value>
    </variable>
    <variable name="LOCAL_FILES_FILTERED_OUT" basic="false">
      <value>"vssver.scc"</value>
    </variable>
    <variable name="WRAPPER" basic="false">
      <value>vcs.list.VssListCommand.class</value>
    </variable>
    <variable name="OPTIONS" basic="false">
      <value>-I- ${IDENT}</value>
    </variable>
    <variable name="NUR" basic="false">
      <value>"</value>
    </variable>
    <variable name="SHOWLOCALFILES" basic="false">
      <value>true</value>
    </variable>
    <variable name="PS" basic="false">
      <value>${path.separator}</value>
      <value if="IS_WIN9X">/</value>
    </variable>
    <variable name="USER_LOCAL_PARAM_LABELS" basic="false">
      <value>"VSS command options"</value>
    </variable>
    <variable name="RUN_REFRESH" basic="false">
      <value>cmd /X /C "cd /D $[? EMPTY_REFRESH_FOLDER] [${EMPTY_REFRESH_FOLDER}] [\"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\"] &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp; $[? EMPTY_REFRESH_FOLDER] [] [\"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp;]</value>
      <value if="IS_WIN9X">${SHELL} -c "cd $[? EMPTY_REFRESH_FOLDER] [${EMPTY_REFRESH_FOLDER_\/}] [${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE}] &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp; $[? EMPTY_REFRESH_FOLDER] [] [${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp;]</value>
    </variable>
    <variable name="RUN" basic="false">
      <value>cmd /X /C "(mkdir \"${ROOTDIR}${PS}${MODULE}${PS}${DIR}${PS}.\" 2>nul || echo.) &amp;&amp; cd /D \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp; \"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "mkdir -p ${QUOTE}${ROOTDIR_\/}${PS}${MODULE_\/}${PS}${DIR_\/}${PS}.${QUOTE}; cd ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp;</value>
    </variable>
    <variable name="RUN_SILENT" basic="false">
      <value>cmd /X /C "(mkdir \"${ROOTDIR}${PS}${MODULE}${PS}${DIR}${PS}.\" 2>nul || echo. >nul) &amp;&amp; cd /D \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" >nul &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" >nul &amp;&amp; \"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" >nul &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "mkdir -p ${QUOTE}${ROOTDIR_\/}${PS}${MODULE_\/}${PS}${DIR_\/}${PS}.${QUOTE}; cd ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} >/dev/null &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} >/dev/null &amp;&amp;</value>
    </variable>
    <variable name="RUN_NMK" basic="false">
      <value>cmd /X /C "cd /D \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp; \"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "cd ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp;</value>
    </variable>
    <variable name="RUNCDM" basic="false">
      <value>cmd /X /C "(mkdir \"${ROOTDIR}${PS}${MODULE}${PS}.\" 2>nul || echo.) &amp;&amp; cd /D \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []\" &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}$[? MODULE] [${PS}${MODULE}] []\" &amp;&amp; \"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []\" &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "mkdir -p ${QUOTE}${ROOTDIR_\/}${PS}${MODULE_\/}${PS}.${QUOTE}; cd ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []${QUOTE} &amp;&amp;</value>
    </variable>
    <variable name="RUNCDM_SILENT" basic="false">
      <value>cmd /X /C "(mkdir \"${ROOTDIR}${PS}${MODULE}${PS}.\" 2>nul || echo. >nul) &amp;&amp; cd /D \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []\" >nul &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}$[? MODULE] [${PS}${MODULE}] []\" >nul &amp;&amp; \"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []\" >nul &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "mkdir -p ${QUOTE}${ROOTDIR_\/}${PS}${MODULE_\/}${PS}.${QUOTE} >/dev/null; cd ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []${QUOTE} >/dev/null &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []${QUOTE} >/dev/null &amp;&amp;</value>
    </variable>
    <variable name="RUN_GLOBAL" basic="false">
      <value>cmd /X /C "cd /D \"${ROOTDIR}\" &amp;&amp; \"${VSSCMD}\" cd ${OPTIONS} \"${PROJECT}\" &amp;&amp; \"${VSSCMD}\" workfold ${OPTIONS} \"${ROOTDIR}\" &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "cd ${QUOTE}${ROOTDIR_\/}${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} cd ${OPTIONS} ${QUOTE}${PROJECT_\/}${QUOTE} &amp;&amp; ${QUOTE}${VSSCMD_\/}${QUOTE} workfold ${OPTIONS} ${QUOTE}${ROOTDIR_\/}${QUOTE} &amp;&amp;</value>
    </variable>
    <variable name="QUOTE" basic="false">
      <value>\"</value>
      <value if="IS_WIN9X">\"\"</value>
    </variable>
    <variable name="IDENT" basic="false">
      <value>-Y${USER_NAME},${PASSWORD}</value>
    </variable>
    <variable name="WORKPROJ" basic="false">
      <value>${PROJECT}$[? MODULE] [${PS}${MODULE}] []$[? PATH] [${PS}${PATH}] []</value>
      <value if="IS_WIN9X">${PROJECT_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? PATH] [${PS}${PATH_\/}] []</value>
    </variable>
    <variable name="POSSIBLE_FILE_STATUSES" basic="false">
      <value>"Current", "Missing", "Locally Modified"</value>
    </variable>
    <variable name="VCS_FILE_STATUS_MISSING" basic="false">
      <value>Missing</value>
    </variable>
    <variable name="VCS_FOLDER_STATUS_MISSING" basic="false">
      <value>Missing</value>
    </variable>
    <variable name="ICONS_FOR_FILE_STATUSES" basic="false">
      <value>"vcs/resources/badgeUpToDate.gif", "vcs/resources/badgeNeedsCheckout.gif"</value>
    </variable>
    <variable name="RUNSIMPLE" basic="false">
      <value>cmd /X /C "cd /D \"${ROOTDIR}$[? MODULE] [${PS}${MODULE}] []$[? DIR] [${PS}${DIR}] []\" &amp;&amp;</value>
      <value if="IS_WIN9X">${SHELL} -c "cd ${QUOTE}${ROOTDIR_\/}$[? MODULE] [${PS}${MODULE_\/}] []$[? DIR] [${PS}${DIR_\/}] []${QUOTE} &amp;&amp;</value>
    </variable>
    <variable name="POSSIBLE_FILE_STATUSES_LOCALIZED" basic="false">
