=== svenreimers/hg-netbeans-org-main-contrib/corba/src/org/netbeans/modules/corba/resources/impls/ORBSettings.dtd
<?xml version='1.0' encoding='ISO-8859-1'?>

<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE orb-settings SYSTEM "ORBSettings.dtd">

    <orb-settings>
    ...
    </orb-settings>
-->

  <!ELEMENT policies-header EMPTY>
  <!ATTLIST policies-header
    value CDATA #IMPLIED
  >

  <!ELEMENT get-root-poa-pattern EMPTY>
  <!ATTLIST get-root-poa-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT servant-class EMPTY>
  <!ATTLIST servant-class
    value CDATA #IMPLIED
  >

  <!ELEMENT orb-settings (client-binding|server-binding|local-bundle|poa-settings|java-template-code|idl-template-code|impl-generator-settings|idl-compiler-settings)*>
  <!ATTLIST orb-settings
    supported CDATA #IMPLIED
    tag CDATA #IMPLIED
    name CDATA #IMPLIED
  >

  <!ELEMENT poa-settings (set-poa-activator|unrecognized-policy|section-init-servants|section-activate-poas|poa-policy|poa-activator-pattern|policies-footer|servant-class|poa-pattern|root-poa-init|create-servant-instance|servant-instance-pattern|policies-declaration-pattern|policies-header|create-poa|root-poa-pattern|policies-declaration|set-servant-manager|default-servant-pattern|servant-manager-pattern|policies-separator|servant-pattern|policies-header-pattern|policies-footer-pattern|set-default-servant|get-root-poa-pattern|activate-poa|section-init-poas|activate-servant-with-user-id|get-poa-manager|activate-servant-with-system-id|default-default-servant-var-name|default-poa-activator-var-name|default-poa-name|default-poa-var-name|default-servant-id|default-servant-id-var-name|default-servant-var-name|default-servant-manager-var-name)*>

  <!ELEMENT poa-activator-pattern EMPTY>
  <!ATTLIST poa-activator-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT compiler EMPTY>
  <!ATTLIST compiler
    value CDATA #IMPLIED
  >

  <!ELEMENT import (#PCDATA)>

  <!ELEMENT section-init-poas EMPTY>
  <!ATTLIST section-init-poas
    value CDATA #IMPLIED
  >

  <!ELEMENT tie-impl-prefix EMPTY>
  <!ATTLIST tie-impl-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT ext-class-prefix EMPTY>
  <!ATTLIST ext-class-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT code (#PCDATA)>

  <!ELEMENT root-poa-init EMPTY>
  <!ATTLIST root-poa-init
    value CDATA #IMPLIED
  >

  <!ELEMENT create-servant-instance EMPTY>
  <!ATTLIST create-servant-instance
    value CDATA #IMPLIED
  >

  <!ELEMENT file-position EMPTY>
  <!ATTLIST file-position
    value CDATA #IMPLIED
  >

  <!ELEMENT idl-template-code (template-code)*>

  <!ELEMENT message-position EMPTY>
  <!ATTLIST message-position
    value CDATA #IMPLIED
  >

  <!ELEMENT policies-footer EMPTY>
  <!ATTLIST policies-footer
    value CDATA #IMPLIED
  >

  <!ELEMENT line-position EMPTY>
  <!ATTLIST line-position
    value CDATA #IMPLIED
  >

  <!ELEMENT impl-int-postfix EMPTY>
  <!ATTLIST impl-int-postfix
    value CDATA #IMPLIED
  >

  <!ELEMENT tie-impl-postfix EMPTY>
  <!ATTLIST tie-impl-postfix
    value CDATA #IMPLIED
  >

  <!ELEMENT package-param EMPTY>
  <!ATTLIST package-param
    value CDATA #IMPLIED
  >

  <!ELEMENT tie-param EMPTY>
  <!ATTLIST tie-param
    value CDATA #IMPLIED
  >

  <!ELEMENT disable-action EMPTY>
  <!ATTLIST disable-action
    name CDATA #IMPLIED
  >

  <!ELEMENT error-expression EMPTY>
  <!ATTLIST error-expression
    value CDATA #IMPLIED
  >

  <!ELEMENT prepare-code-pattern EMPTY>
  <!ATTLIST prepare-code-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT activate-poa EMPTY>
  <!ATTLIST activate-poa
    value CDATA #IMPLIED
  >

  <!ELEMENT poa-policy (prepare-code|create-code-pattern|prepare-code-pattern|create-code|value)*>
  <!ATTLIST poa-policy
    name CDATA #IMPLIED
    mnemonic_character CDATA #IMPLIED
  >

  <!ELEMENT implbase-impl-prefix EMPTY>
  <!ATTLIST implbase-impl-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT value-impl-prefix EMPTY>
  <!ATTLIST value-impl-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT value-impl-postfix EMPTY>
  <!ATTLIST value-impl-postfix
    value CDATA #IMPLIED
  >

  <!ELEMENT valuefactory-impl-prefix EMPTY>
  <!ATTLIST valuefactory-impl-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT valuefactory-impl-postfix EMPTY>
  <!ATTLIST valuefactory-impl-postfix
    value CDATA #IMPLIED
  >

  <!ELEMENT require-policy EMPTY>
  <!ATTLIST require-policy
    name CDATA #IMPLIED
    value CDATA #IMPLIED
  >

  <!ELEMENT section-init-servants EMPTY>
  <!ATTLIST section-init-servants
    value CDATA #IMPLIED
  >

  <!ELEMENT create-code-pattern EMPTY>
  <!ATTLIST create-code-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT policies-separator EMPTY>
  <!ATTLIST policies-separator
    value CDATA #IMPLIED
  >

  <!ELEMENT template-code (#PCDATA)>
  <!ATTLIST template-code
    name CDATA #IMPLIED
  >

  <!ELEMENT patch-code (#PCDATA)>
  <!ATTLIST patch-code
    value CDATA #IMPLIED
  >

  <!ELEMENT ext-class-postfix EMPTY>
  <!ATTLIST ext-class-postfix
    value CDATA #IMPLIED
  >

  <!ELEMENT policies-header-pattern EMPTY>
  <!ATTLIST policies-header-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT policies-declaration EMPTY>
  <!ATTLIST policies-declaration
    value CDATA #IMPLIED
  >

  <!ELEMENT idl-compiler-settings (compiler|package-delimiter|dir-param|column-position|line-position|file-position|error-expression|message-position|package-param|tie-param)*>

  <!ELEMENT policies-footer-pattern EMPTY>
  <!ATTLIST policies-footer-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT policies-declaration-pattern EMPTY>
  <!ATTLIST policies-declaration-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT dir-param EMPTY>
  <!ATTLIST dir-param
    value CDATA #IMPLIED
  >

  <!ELEMENT section-activate-poas EMPTY>
  <!ATTLIST section-activate-poas
    value CDATA #IMPLIED
  >

  <!ELEMENT impl-generator-settings (ext-class-postfix|implbase-impl-prefix|impl-int-postfix|implbase-impl-postfix|tie-impl-postfix|tie-impl-prefix|impl-int-prefix|ext-class-prefix|value-impl-prefix|value-impl-postfix|valuefactory-impl-prefix|valuefactory-impl-postfix|tie-class-prefix|tie-class-postfix)*>

  <!ELEMENT column-position EMPTY>
  <!ATTLIST column-position
    value CDATA #IMPLIED
  >

  <!ELEMENT prepare-code (#PCDATA)>

  <!ELEMENT client-binding (import|code|wizard-requires|wizard-does-not-support|binding-template-code)*>
  <!ATTLIST client-binding
    name CDATA #IMPLIED
    template-tag CDATA #IMPLIED
    local-tag CDATA #IMPLIED
  >

  <!ELEMENT set-default-servant EMPTY>
  <!ATTLIST set-default-servant
    value CDATA #IMPLIED
  >

  <!ELEMENT impl-int-prefix EMPTY>
  <!ATTLIST impl-int-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT package-delimiter EMPTY>
  <!ATTLIST package-delimiter
    value CDATA #IMPLIED
  >

  <!ELEMENT create-code (#PCDATA)>

  <!ELEMENT set-poa-activator EMPTY>
  <!ATTLIST set-poa-activator
    value CDATA #IMPLIED
  >

  <!ELEMENT create-poa EMPTY>
  <!ATTLIST create-poa
    value CDATA #IMPLIED
  >

  <!ELEMENT servant-instance-pattern EMPTY>
  <!ATTLIST servant-instance-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT unrecognized-policy EMPTY>
  <!ATTLIST unrecognized-policy
    value CDATA #IMPLIED
  >

  <!ELEMENT value (require-policy|disable-action|conflicts-with-policy)*>
  <!ATTLIST value
    name CDATA #IMPLIED
  >

  <!ELEMENT servant-pattern EMPTY>
  <!ATTLIST servant-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT java-template-code (template-code|patch-code)*>

  <!ELEMENT conflicts-with-policy EMPTY>
  <!ATTLIST conflicts-with-policy
    name CDATA #IMPLIED
    value CDATA #IMPLIED
  >

  <!ELEMENT activate-servant-with-system-id EMPTY>
  <!ATTLIST activate-servant-with-system-id
    value CDATA #IMPLIED
  >

  <!ELEMENT set-servant-manager EMPTY>
  <!ATTLIST set-servant-manager
    value CDATA #IMPLIED
  >

  <!ELEMENT activate-servant-with-user-id EMPTY>
  <!ATTLIST activate-servant-with-user-id
    value CDATA #IMPLIED
  >

  <!ELEMENT servant-manager-pattern EMPTY>
  <!ATTLIST servant-manager-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT server-binding (import|code|wizard-requires|wizard-does-not-support|binding-template-code)*>
  <!ATTLIST server-binding
    name CDATA #IMPLIED
    template-tag CDATA #IMPLIED
    local-tag CDATA #IMPLIED
  >

  <!ELEMENT local-bundle EMPTY>
  <!ATTLIST local-bundle
    value CDATA #IMPLIED
  >

  <!ELEMENT root-poa-pattern EMPTY>
  <!ATTLIST root-poa-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT implbase-impl-postfix EMPTY>
  <!ATTLIST implbase-impl-postfix
    value CDATA #IMPLIED
  >

  <!ELEMENT default-servant-pattern EMPTY>
  <!ATTLIST default-servant-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT poa-pattern EMPTY>
  <!ATTLIST poa-pattern
    value CDATA #IMPLIED
  >

  <!ELEMENT get-poa-manager EMPTY>
  <!ATTLIST get-poa-manager
    value CDATA #IMPLIED
  >

  <!ELEMENT default-default-servant-var-name EMPTY>
  <!ATTLIST default-default-servant-var-name
    value CDATA #IMPLIED
  >

  <!ELEMENT default-poa-activator-var-name EMPTY>
  <!ATTLIST default-poa-activator-var-name
    value CDATA #IMPLIED
  >

  <!ELEMENT default-poa-name EMPTY>
  <!ATTLIST default-poa-name
    value CDATA #IMPLIED
  >

  <!ELEMENT default-poa-var-name EMPTY>
  <!ATTLIST default-poa-var-name
    value CDATA #IMPLIED
  >

  <!ELEMENT default-servant-id EMPTY>
  <!ATTLIST default-servant-id
    value CDATA #IMPLIED
  >

  <!ELEMENT default-servant-id-var-name EMPTY>
  <!ATTLIST default-servant-id-var-name
    value CDATA #IMPLIED
  >

  <!ELEMENT default-servant-var-name EMPTY>
  <!ATTLIST default-servant-var-name
    value CDATA #IMPLIED
  >

  <!ELEMENT default-servant-manager-var-name EMPTY>
  <!ATTLIST default-servant-manager-var-name
    value CDATA #IMPLIED
  >

  <!ELEMENT wizard-requires EMPTY>
  <!ATTLIST wizard-requires
    value CDATA #IMPLIED
    title CDATA #IMPLIED
    type  CDATA #IMPLIED
  >

  <!ELEMENT wizard-does-not-support EMPTY>

  <!ELEMENT binding-template-code (#PCDATA)>
  <!ATTLIST binding-template-code
    name CDATA #IMPLIED
  >

  <!ELEMENT tie-class-prefix EMPTY>
  <!ATTLIST tie-class-prefix
    value CDATA #IMPLIED
  >

  <!ELEMENT tie-class-postfix EMPTY>
  <!ATTLIST tie-class-postfix
    value CDATA #IMPLIED
  >

=== svenreimers/hg-netbeans-org-main-contrib/corba/src/org/netbeans/modules/corba/resources/impls/orbixweb.xml
<?xml version="1.0" encoding='ISO-8859-1'?>
<!--
                Sun Public License Notice

The contents of this file are subject to the Sun Public License
Version 1.0 (the "License"). You may not use this file except in
compliance with the License. A copy of the License is available at
http://www.sun.com/

The Original Code is NetBeans. The Initial Developer of the Original
Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
Microsystems, Inc. All Rights Reserved.
-->


<!DOCTYPE orb-settings PUBLIC "-//Forte for Java//DTD ORBSettings 1.0//EN" "ORBSettings.dtd"[
<!ENTITY corba20-generic-impl SYSTEM "corba20-generic-impl.ent">
]>
<orb-settings name='OrbixWeb 3.2' tag='orbixweb32' supported='true'>
  
  &corba20-generic-impl;

  <java-template-code>

    <!--
    
  <template-code name='SERVER_IMPORT'>
    <![CDATA[import IE.Iona.OrbixWeb._OrbixWeb;
    import IE.Iona.OrbixWeb._CORBA;
    
    import org.omg.CORBA.ORB;
    import org.omg.CORBA.ORBPackage.InvalidName;
    import org.omg.CORBA.SystemException;
    
    import java.util.Properties;]]>
  </template-code>
    
    
  <template-code name='CLIENT_IMPORT'>
    <![CDATA[import IE.Iona.OrbixWeb._OrbixWeb;
    import IE.Iona.OrbixWeb._CORBA;
    
    import org.omg.CORBA.ORB;
    import org.omg.CORBA.ORBPackage.InvalidName;
    import org.omg.CORBA.SystemException;
    
    import java.util.Properties;]]>
  </template-code>
    -->

  <template-code name='ORB_PROPERTIES'>
    <![CDATA[// setting system properties is necessary to use OrbixWeb in Java 1.2
      Properties props = System.getProperties ();
      props.put ("org.omg.CORBA.ORBClass", "IE.Iona.OrbixWeb.CORBA.ORB");
      props.put ("org.omg.CORBA.ORBSingletonClass", "IE.Iona.OrbixWeb.CORBA.singletonORB");
      System.setProperties (props);]]>
  </template-code>

  </java-template-code>


  <server-binding name='Proprietary Binder' template-tag='SERVER_BINDING'>
    <import>
      <![CDATA[import IE.Iona.OrbixWeb._OrbixWeb;
      import IE.Iona.OrbixWeb._CORBA;]]>
    </import>
    <code>
      <![CDATA[//OrbixWeb proprietary server binder
      // to _CORBA.Orbix.impl_is_ready (); -- insert server name
      // (object implemenattion name) between bracket - for example:
      // _CORBA.Orbix.impl_is_ready ("HelloWorld");
      try {
      _CORBA.Orbix.impl_is_ready ("<server name>");
      } catch (SystemException e) {
      e.printStackTrace ();
      }]]>
    </code>
  </server-binding>


  <client-binding name='Proprietary Binder' template-tag='CLIENT_BINDING'>
    <import>
      <![CDATA[import IE.Iona.OrbixWeb._OrbixWeb;
      import IE.Iona.OrbixWeb._CORBA;]]>
    </import>
    <code>
      <![CDATA[//OrbixWeb Client binder binding
      try {
      // use <class> <name> = <class>Helper.bind (":<name>", args[0]);
      // args[0] is name of host where server run.
      } catch (SystemException e) {
        e.printStackTrace ();
      }]]>
    </code>
  </client-binding>


  <idl-compiler-settings>
    <tie-param value=''/>
    <dir-param value='-jO'/>
    <package-param value='-jP'/>
    <compiler value='java -classpath {classpath}{:}{library} org.netbeans.modules.corba.idl.compiler.orbix32.Compiler {params} {dir_param} {package_root} {package_param} {package} {files}'/>
    <package-delimiter value='.'/>
    <error-expression value='^([^ ]+):([0-9]+):(.*)'/>
    <file-position value='1'/>
    <line-position value='2'/>
    <column-position value='-1'/>
    <message-position value='3'/>
    
  </idl-compiler-settings>

</orb-settings>

=== svenreimers/hg-netbeans-org-main-contrib/corba/src/org/netbeans/modules/corba/resources/impls/orbix2000.xml
<?xml version="1.0" encoding='ISO-8859-1'?>
<!--
                Sun Public License Notice

The contents of this file are subject to the Sun Public License
Version 1.0 (the "License"). You may not use this file except in
compliance with the License. A copy of the License is available at
http://www.sun.com/

The Original Code is NetBeans. The Initial Developer of the Original
Code is Sun Microsystems, Inc. Portions Copyright 1997-2001 Sun
Microsystems, Inc. All Rights Reserved.
-->


<!DOCTYPE orb-settings PUBLIC "-//Forte for Java//DTD ORBSettings 1.0//EN" "ORBSettings.dtd"[
<!ENTITY corba23-poa SYSTEM "corba23-poa.ent">
<!ENTITY corba23-generic-impl SYSTEM "corba23-generic-impl.ent">
]>
<orb-settings name='Orbix2000 for Java 1.x' tag='orbix20004j' supported='true'>
  
  &corba23-poa;
  &corba23-generic-impl;

  <java-template-code>
    <template-code name='ORB_PROPERTIES'>
      <![CDATA[// setting system properties is necessary to use Orbix 2000 for Java 1.0
      Properties props = System.getProperties ();
      props.put ("org.omg.CORBA.ORBClass", "com.iona.corba.art.artimpl.ORBImpl");
      props.put ("org.omg.CORBA.ORBSingletonClass", "com.iona.corba.art.artimpl.ORBSingleton");
      System.setProperties (props);]]>
    </template-code>
  </java-template-code>

  <idl-compiler-settings>
    <tie-param value=''/>
    <dir-param value='-O'/>
    <package-param value='-P'/>
    <compiler value='idl {params} -jbase:{dir_param}{package_root}:{package_param}{package} -jpoa:{dir_param}{package_root}:{package_param}{package} {files}'/>
    <package-delimiter value='.'/>
    <error-expression value='^idl: "([^ ]+)", line ([0-9]+): (.*)'/>
    <file-position value='1'/>
    <line-position value='2'/>
    <column-position value='-1'/>
    <message-position value='3'/>
    
  </idl-compiler-settings>
    
    
</orb-settings>

=== svenreimers/hg-netbeans-org-main-contrib/corba/src/org/netbeans/modules/corba/resources/impls/j2ee-orb.xml
<?xml version="1.0" encoding='ISO-8859-1'?>
<!--
The contents of this file are subject to the terms of the Common Development
and Distribution License (the License). You may not use this file except in
compliance with the License.

You can obtain a copy of the License at http://www.netbeans.org/cddl.html
or http://www.netbeans.org/cddl.txt.

When distributing Covered Code, include this CDDL Header Notice in each file
and include the License file at http://www.netbeans.org/cddl.txt.
If applicable, add the following below the CDDL Header, with the fields
enclosed by brackets [] replaced by your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

The Original Software is NetBeans. The Initial Developer of the Original
Software is Sun Microsystems, Inc. Portions Copyright 1997-2006 Sun
Microsystems, Inc. All Rights Reserved.
-->


<!DOCTYPE orb-settings PUBLIC "-//Forte for Java//DTD ORBSettings 1.0//EN" "ORBSettings.dtd"[
<!ENTITY corba20-generic-impl SYSTEM "nbres:/org/netbeans/modules/corba/resources/impls/corba20-generic-impl.ent">
]>
<orb-settings name='J2EE ORB' tag='j2ee' supported='true'>

  &corba20-generic-impl;

  <idl-compiler-settings>
    <tie-param value='--tie'/>
    <dir-param value='--directory'/>
    <package-param value='--package'/>
    <compiler value='java -classpath {classpath}{:}{library} org.netbeans.modules.corba.idl.compiler.j2ee.Compiler {cpp_params} {params} {dir_param} {package_root} {package_param} {package} {files}'/>
    <package-delimiter value='.'/>
    <error-expression value='^([^ \n]+) \(line ([0-9]+)\): (.*)'/>
    <file-position value='1'/>
    <line-position value='2'/>
    <column-position value='-1'/>
    <message-position value='3'/>
      
  </idl-compiler-settings>

</orb-settings>
